# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddInvoices.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class WindowAddInvoices(QtWidgets.QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(348, 372)
        Form.setWindowTitle("")
        self.pushButton_add_invoices = QtWidgets.QPushButton(Form)
        self.pushButton_add_invoices.setGeometry(QtCore.QRect(60, 330, 80, 26))
        self.pushButton_add_invoices.setObjectName("pushButton_add_invoices")
        self.pushButton_cancel_invoices = QtWidgets.QPushButton(Form)
        self.pushButton_cancel_invoices.setGeometry(QtCore.QRect(220, 330, 80, 26))
        self.pushButton_cancel_invoices.setObjectName("pushButton_cancel_invoices")
        self.lineEdit_invoices = QtWidgets.QLineEdit(Form)
        self.lineEdit_invoices.setGeometry(QtCore.QRect(30, 40, 291, 26))
        self.lineEdit_invoices.setObjectName("lineEdit_invoices")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 10, 121, 31))
        self.label.setObjectName("label")
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setGeometry(QtCore.QRect(50, 80, 241, 221))
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_add_invoices.setText(_translate("Form", "Добавить "))
        self.pushButton_cancel_invoices.setText(_translate("Form", "Отмена "))
        self.label.setText(_translate("Form", "номер в накладных"))
