# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chanceProvader.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddProvaderchance(QtWidgets.QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(299, 266)
        self.label_name_provader = QtWidgets.QLabel(Form)
        self.label_name_provader.setGeometry(QtCore.QRect(10, -10, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_name_provader.setFont(font)
        self.label_name_provader.setObjectName("label_name_provader")
        self.label_adress_pv = QtWidgets.QLabel(Form)
        self.label_adress_pv.setGeometry(QtCore.QRect(20, 90, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_adress_pv.setFont(font)
        self.label_adress_pv.setObjectName("label_adress_pv")
        self.pushButton_chance_pv = QtWidgets.QPushButton(Form)
        self.pushButton_chance_pv.setGeometry(QtCore.QRect(20, 210, 80, 26))
        self.pushButton_chance_pv.setObjectName("pushButton_chance_pv")
        self.pushButton_cansel_pv = QtWidgets.QPushButton(Form)
        self.pushButton_cansel_pv.setGeometry(QtCore.QRect(190, 210, 80, 26))
        self.pushButton_cansel_pv.setObjectName("pushButton_cansel_pv")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 261, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 140, 271, 26))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_name_provader.setText(_translate("Form", "название "))
        self.label_adress_pv.setText(_translate("Form", "Адрес"))
        self.pushButton_chance_pv.setText(_translate("Form", "изменить"))
        self.pushButton_cansel_pv.setText(_translate("Form", "отмена"))
