# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changeInvoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Change2(QtWidgets.QWidget):
    def setupUi(self, change2):
        change2.setObjectName("change2")
        change2.resize(265, 243)
        self.nomer = QtWidgets.QLabel(change2)
        self.nomer.setGeometry(QtCore.QRect(20, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nomer.setFont(font)
        self.nomer.setObjectName("nomer")
        self.label_data = QtWidgets.QLabel(change2)
        self.label_data.setGeometry(QtCore.QRect(10, 90, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_data.setFont(font)
        self.label_data.setObjectName("label_data")
        self.lineEdit_number = QtWidgets.QLineEdit(change2)
        self.lineEdit_number.setGeometry(QtCore.QRect(0, 50, 261, 31))
        self.lineEdit_number.setObjectName("lineEdit_number")
        self.lineEdit_add_data = QtWidgets.QLineEdit(change2)
        self.lineEdit_add_data.setGeometry(QtCore.QRect(0, 140, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_add_data.setFont(font)
        self.lineEdit_add_data.setObjectName("lineEdit_add_data")
        self.pb_add_invoice = QtWidgets.QPushButton(change2)
        self.pb_add_invoice.setGeometry(QtCore.QRect(10, 200, 80, 26))
        self.pb_add_invoice.setObjectName("pb_add_invoice")
        self.pb_cansel_invoice = QtWidgets.QPushButton(change2)
        self.pb_cansel_invoice.setGeometry(QtCore.QRect(170, 200, 80, 26))
        self.pb_cansel_invoice.setObjectName("pb_cansel_invoice")

        self.retranslateUi(change2)
        QtCore.QMetaObject.connectSlotsByName(change2)

    def retranslateUi(self, change2):
        _translate = QtCore.QCoreApplication.translate
        change2.setWindowTitle(_translate("change2", "изменение данных"))
        self.nomer.setText(_translate("change2", "номер "))
        self.label_data.setText(_translate("change2", "данные "))
        self.pb_add_invoice.setText(_translate("change2", "изменить"))
        self.pb_cansel_invoice.setText(_translate("change2", "отмена "))
