# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteInvoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DeleteInvoice(QtWidgets.QMainWindow):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(428, 146)
        self.pushButton_invoice_yes = QtWidgets.QPushButton(Form2)
        self.pushButton_invoice_yes.setGeometry(QtCore.QRect(40, 90, 80, 26))
        self.pushButton_invoice_yes.setObjectName("pushButton_invoice_yes")
        self.pushButton_invoice_cansel = QtWidgets.QPushButton(Form2)
        self.pushButton_invoice_cansel.setGeometry(QtCore.QRect(260, 90, 80, 26))
        self.pushButton_invoice_cansel.setObjectName("pushButton_invoice_cansel")
        self.label_invoice = QtWidgets.QLabel(Form2)
        self.label_invoice.setGeometry(QtCore.QRect(10, 20, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_invoice.setFont(font)
        self.label_invoice.setObjectName("label_invoice")

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Удаление данных в накладных"))
        self.pushButton_invoice_yes.setText(_translate("Form2", "да "))
        self.pushButton_invoice_cansel.setText(_translate("Form2", "нет"))
        self.label_invoice.setText(_translate("Form2", "Вы хотите удалить строчку ?"))
