# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_pv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DeleteProvader(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(427, 121)
        font = QtGui.QFont()
        font.setPointSize(16)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 20, 391, 18))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_delete_pd_yes = QtWidgets.QPushButton(Form)
        self.pushButton_delete_pd_yes.setGeometry(QtCore.QRect(30, 90, 80, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.pushButton_delete_pd_yes.setFont(font)
        self.pushButton_delete_pd_yes.setStyleSheet("background-color: rgb(38, 162, 105);")
        self.pushButton_delete_pd_yes.setObjectName("pushButton_delete_pd_yes")
        self.pushButton_canse_no = QtWidgets.QPushButton(Form)
        self.pushButton_canse_no.setGeometry(QtCore.QRect(290, 90, 80, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_canse_no.setFont(font)
        self.pushButton_canse_no.setStyleSheet("background-color: rgb(192, 28, 40);")
        self.pushButton_canse_no.setObjectName("pushButton_canse_no")
        self.pushButton_delete_pd_yes.clicked.connect(self.OKAction)
        self.pushButton_canse_no.clicked.connect(self.CancelAction)
 
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Удаление данные"))
        self.label.setText(_translate("Form", "Вы действительно хотите удалить строчку?"))
        self.pushButton_delete_pd_yes.setText(_translate("Form", "да"))
        self.pushButton_canse_no.setText(_translate("Form", "нет"))
 