# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(300, 383)
        self.pushButton_auth = QtWidgets.QPushButton(Form2)
        self.pushButton_auth.setGeometry(QtCore.QRect(10, 280, 271, 26))
        self.pushButton_auth.setObjectName("pushButton_auth")
        self.pushButton_exit = QtWidgets.QPushButton(Form2)
        self.pushButton_exit.setGeometry(QtCore.QRect(10, 320, 271, 26))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_lg = QtWidgets.QLabel(Form2)
        self.label_lg.setGeometry(QtCore.QRect(10, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_lg.setFont(font)
        self.label_lg.setObjectName("label_lg")
        self.label_ps = QtWidgets.QLabel(Form2)
        self.label_ps.setGeometry(QtCore.QRect(20, 160, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_ps.setFont(font)
        self.label_ps.setObjectName("label_ps")
        self.lineEdit_psw = QtWidgets.QLineEdit(Form2)
        self.lineEdit_psw.setGeometry(QtCore.QRect(10, 210, 291, 26))
        self.lineEdit_psw.setObjectName("lineEdit_psw")
        self.lineEdit_log = QtWidgets.QLineEdit(Form2)
        self.lineEdit_log.setGeometry(QtCore.QRect(10, 90, 271, 26))
        self.lineEdit_log.setObjectName("lineEdit_log")

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Form"))
        self.pushButton_auth.setText(_translate("Form2", "Вход"))
        self.pushButton_exit.setText(_translate("Form2", "выход"))
        self.label_lg.setText(_translate("Form2", "логин"))
        self.label_ps.setText(_translate("Form2", "пароль"))
