# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class addWindow2(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1229, 909)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pb_add_tovar = QtWidgets.QPushButton(self.centralwidget)
        self.pb_add_tovar.setGeometry(QtCore.QRect(430, 60, 80, 26))
        self.pb_add_tovar.setObjectName("pb_add_tovar")
        self.pushButton_change_tovar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_change_tovar.setGeometry(QtCore.QRect(430, 100, 80, 26))
        self.pushButton_change_tovar.setObjectName("pushButton_change_tovar")
        self.pushButton_delete_tovar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete_tovar.setGeometry(QtCore.QRect(430, 140, 80, 26))
        self.pushButton_delete_tovar.setObjectName("pushButton_delete_tovar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(550, 40, 471, 841))
        self.tableView.setObjectName("tableView")
        self.pb_add2 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_add2.setGeometry(QtCore.QRect(1040, 50, 80, 26))
        self.pb_add2.setObjectName("pb_add2")
        self.pb_change2 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_change2.setGeometry(QtCore.QRect(1040, 90, 80, 26))
        self.pb_change2.setObjectName("pb_change2")
        self.pb_delete2 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_delete2.setGeometry(QtCore.QRect(1040, 120, 80, 26))
        self.pb_delete2.setObjectName("pb_delete2")
        self.pb_window2 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_window2.setGeometry(QtCore.QRect(1140, 10, 80, 26))
        self.pb_window2.setObjectName("pb_window2")
        self.tableView_2 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_2.setGeometry(QtCore.QRect(10, 40, 401, 841))
        self.tableView_2.setObjectName("tableView_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Товары "))
        self.pb_add_tovar.setText(_translate("MainWindow", "добавить"))
        self.pushButton_change_tovar.setText(_translate("MainWindow", "изменить"))
        self.pushButton_delete_tovar.setText(_translate("MainWindow", "Удалить"))
        self.label_2.setText(_translate("MainWindow", "Накладные "))
        self.pb_add2.setText(_translate("MainWindow", "добавить"))
        self.pb_change2.setText(_translate("MainWindow", "Изменить"))
        self.pb_delete2.setText(_translate("MainWindow", "удалить"))
        self.pb_window2.setText(_translate("MainWindow", "другое"))
