# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1294, 927)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 440, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(790, 0, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tableView_provader = QtWidgets.QTableView(self.centralwidget)
        self.tableView_provader.setGeometry(QtCore.QRect(0, 20, 411, 411))
        self.tableView_provader.setObjectName("tableView_provader")
        self.tableView_invoices = QtWidgets.QTableView(self.centralwidget)
        self.tableView_invoices.setGeometry(QtCore.QRect(0, 470, 411, 401))
        self.tableView_invoices.setObjectName("tableView_invoices")
        self.pushButton_add_provader = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_provader.setGeometry(QtCore.QRect(430, 30, 80, 26))
        self.pushButton_add_provader.setObjectName("pushButton_add_provader")
        self.pushButton_delete_provader = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete_provader.setGeometry(QtCore.QRect(430, 70, 80, 26))
        self.pushButton_delete_provader.setObjectName("pushButton_delete_provader")
        self.pushButton_add_invoices = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_invoices.setGeometry(QtCore.QRect(420, 680, 91, 31))
        self.pushButton_add_invoices.setObjectName("pushButton_add_invoices")
        self.pushButton_delete_invoices = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete_invoices.setGeometry(QtCore.QRect(420, 740, 101, 31))
        self.pushButton_delete_invoices.setObjectName("pushButton_delete_invoices")
        self.pushButton_add_tovar_invoices = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_tovar_invoices.setGeometry(QtCore.QRect(1190, 30, 80, 26))
        self.pushButton_add_tovar_invoices.setObjectName("pushButton_add_tovar_invoices")
        self.pushButton_delete_tovar_invoices = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete_tovar_invoices.setGeometry(QtCore.QRect(1190, 70, 80, 26))
        self.pushButton_delete_tovar_invoices.setObjectName("pushButton_delete_tovar_invoices")
        self.tableView_tovar_invoices = QtWidgets.QTableView(self.centralwidget)
        self.tableView_tovar_invoices.setGeometry(QtCore.QRect(650, 30, 531, 851))
        self.tableView_tovar_invoices.setObjectName("tableView_tovar_invoices")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Поставщик "))
        self.label_2.setText(_translate("MainWindow", "Накладные"))
        self.label_3.setText(_translate("MainWindow", "Товары в накладных"))
        self.pushButton_add_provader.setText(_translate("MainWindow", "добавить "))
        self.pushButton_delete_provader.setText(_translate("MainWindow", "удалить"))
        self.pushButton_add_invoices.setText(_translate("MainWindow", "добавить "))
        self.pushButton_delete_invoices.setText(_translate("MainWindow", "удалить"))
        self.pushButton_add_tovar_invoices.setText(_translate("MainWindow", "добавить "))
        self.pushButton_delete_tovar_invoices.setText(_translate("MainWindow", "удалять "))
